// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-ZUg6n9_XF8sGNoiLOV3iEe5WjgBbM4',
    appId: '1:1020558899535:web:874e41062e145d04082d3a',
    messagingSenderId: '1020558899535',
    projectId: 'expense-tracker-73da8',
    authDomain: 'expense-tracker-73da8.firebaseapp.com',
    storageBucket: 'expense-tracker-73da8.appspot.com',
    measurementId: 'G-80EB48DGLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5S_KutdgkHqiEfAF5rD1aQTj2h_rhzRk',
    appId: '1:1020558899535:android:de5cbdd4d1a22e0d082d3a',
    messagingSenderId: '1020558899535',
    projectId: 'expense-tracker-73da8',
    storageBucket: 'expense-tracker-73da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaPiY41YkSf28IeZD-ijtEwW4pu8BlfWE',
    appId: '1:1020558899535:ios:734d20a685af8e9f082d3a',
    messagingSenderId: '1020558899535',
    projectId: 'expense-tracker-73da8',
    storageBucket: 'expense-tracker-73da8.appspot.com',
    iosClientId: '1020558899535-ifpjjbv6ogvjt36g721ms8hc9qggvh1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaPiY41YkSf28IeZD-ijtEwW4pu8BlfWE',
    appId: '1:1020558899535:ios:734d20a685af8e9f082d3a',
    messagingSenderId: '1020558899535',
    projectId: 'expense-tracker-73da8',
    storageBucket: 'expense-tracker-73da8.appspot.com',
    iosClientId: '1020558899535-ifpjjbv6ogvjt36g721ms8hc9qggvh1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );
}
